import React from 'react'
import Image from 'next/image'
import { motion } from 'framer-motion'


// import css module
import Style from './Detail.module.css'
import LeftSide from './leftSide'


// import image
import Nodejs from '../image/nodejs-frameworks.webp'
import Head from 'next/head'



const Detail = () => {
  return (
    <>
    <Head>
    <title>S Course</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/src/assets/images/pub/Group 213.svg" />
  </Head>
    <div className={Style.container} >
      <motion.div
      initial={{
        opacity:0 ,
        y:100
      }}
      whileInView={{
        opacity:1 ,
        y:0
      }}
      transition={{
        duration:1.3,
        delay:2
      }}
      viewport={{once:true}}
      className={Style.left}>
        <LeftSide name={"نود جی اس"} rates={"5"}  />
      </motion.div>
      <motion.div 
      initial={{
        opacity:0 ,
        y:100
      }}
      whileInView={{
        opacity:1 ,
        y:0
      }}
      transition={{
        duration:1.3,
        delay:2.2
      }}
      viewport={{once:true}}
      className={Style.right}>
        <Image src={Nodejs} width={550} style={{borderRadius:"17px",marginTop:"20px"}} /> 
      </motion.div>
    </div>
    </>
  )
}

export default Detail