import React from 'react';
import Image from 'next/image';
import Styles from './courses.module.css'
import CoursesItem from '../../src/components/CoursesItem/courses_item'
import Pagination from '../../src/components/common/Pagination/pagination'
import Header from '../../src/components/Header';
import Footer from '../../src/components/Footer/Footer';
import Search from '../../src/components/Search/search';
import Filter from "../../src/assets/images/filter.png"
import Link from 'next/link';
import Head from 'next/head';
import { motion } from 'framer-motion';

const Courses = () => {
  return (
    <>
        <Head>
        <title>S Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/assets/images/pub/Group 213.svg" />
        </Head>
      <Header />
      <div className={Styles.courses_page}>
        <motion.div 
        initial={{
          y:100,
          opacity:0
        }}
        animate={{
          y:0,
          opacity:1
        }}
        transition={{
          duration:1.8,
          delay:1.1
        }}
        viewport={{once:true}}
        className={Styles.courses_header}>
          <div className={Styles.filter}>
            <Image src={Filter} width={17} height={17} />
          </div>
          <h3 className={Styles.title}>دوره ها</h3>
          <div className={Styles.search}><Search /></div>
        </motion.div>
        <Link href={'coursesDetails'} >
        <motion.div 
        initial={{
          y:100,
          opacity:0
        }}
        animate={{
          y:0,
          opacity:1
        }}
        transition={{
          duration:1.8,
          delay:1.4
        }}
        viewport={{once:true}}    
        className={Styles.courses_items}>
          <CoursesItem />
          <CoursesItem />
          <CoursesItem />
          <CoursesItem />
        </motion.div>
        </Link>
      </div>
      <Footer />
    </>
  )
}

export default Courses