import React from 'react'
import Style from './landing.module.css'
import Header from '../../src/components/Header';
import Section1 from '../../src/components/common/Landing/Section 1/section1';
import Section2 from '../../src/components/common/Landing/Section 2/section2';
import Section3 from '../../src/components/common/Landing/Section 3/section3';
import Section4 from '../../src/components/common/Landing/Section 4/section4';
import Section5 from '../../src/components/common/Landing/Section 5/section5';
import Section6 from '../../src/components/common/Landing/Section 6/section6';
import Footer from '../../src/components/Footer/Footer';
import {motion} from 'framer-motion'
import Head from 'next/head';
import LOGO from '../../src/assets/images/pub/Group 213.svg'
import Nav from '../../src/components/nav/Nav';


const Landing = () => {
  return (
        <>
      <Head>
        <title>S Reactive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={LOGO} />
      </Head>
        <motion.div 
        className={Style.intro}
        initial={{
          opacity:1
        }}
        animate={{
          opacity:1
        }}
        transition={{delay:0.1}}
        >        
        </motion.div>
        <div className={Style.main}>
          <Section1 />
          <Section2 />
          <Section3 />
          <Section4 />
          <Section5 />
          <Section6 />
          <Footer /> 
        </div>

        </>
    )
}

export default Landing;